// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvCLM8ZKZKLTFeZSw8HoJR8ifGRx3vmhA',
    appId: '1:664624648027:web:5236b35fe342ef84f1147e',
    messagingSenderId: '664624648027',
    projectId: 'moappfinal-e10b0',
    authDomain: 'moappfinal-e10b0.firebaseapp.com',
    storageBucket: 'moappfinal-e10b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVdqBsO-FW_eQ4IAQf9_8JLOeSKJm2aTI',
    appId: '1:664624648027:android:68dd27dc4037e8e6f1147e',
    messagingSenderId: '664624648027',
    projectId: 'moappfinal-e10b0',
    storageBucket: 'moappfinal-e10b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaXs-v6nKHDIHqJOvtWghSwCQAlgCHTl0',
    appId: '1:664624648027:ios:51c5a0bcc806b3eff1147e',
    messagingSenderId: '664624648027',
    projectId: 'moappfinal-e10b0',
    storageBucket: 'moappfinal-e10b0.appspot.com',
    iosClientId: '664624648027-uu9nsj5s3qlag5eoe06ioqkk7k3nir0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaXs-v6nKHDIHqJOvtWghSwCQAlgCHTl0',
    appId: '1:664624648027:ios:51c5a0bcc806b3eff1147e',
    messagingSenderId: '664624648027',
    projectId: 'moappfinal-e10b0',
    storageBucket: 'moappfinal-e10b0.appspot.com',
    iosClientId: '664624648027-uu9nsj5s3qlag5eoe06ioqkk7k3nir0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalterm',
  );
}
